# Generated by Django 5.1.3 on 2024-11-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validaciondiseño',
            name='conclusion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
