# Generated by Django 5.1.3 on 2024-11-25 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_validaciondiseño_conclusion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
