# Generated by Django 5.1.3 on 2024-11-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_auditor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='codigo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
