# Generated by Django 5.1.3 on 2024-11-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_control_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='explicacion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
