# Generated by Django 5.1.3 on 2024-11-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_respuesta_explicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='encabezado',
            name='respuesta',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
