# Generated by Django 5.1.3 on 2024-11-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_encabezado_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='clasificacion',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control',
            name='frecuencia',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control',
            name='objetivo',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control',
            name='tipologia',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
