# Generated by Django 5.1.3 on 2024-11-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_control_clasificacion_control_frecuencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='tipologia',
        ),
    ]
