# Generated by Django 5.1.3 on 2024-11-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_remove_control_tipologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='tipologia',
            field=models.CharField(default='Verificacion', max_length=100),
            preserve_default=False,
        ),
    ]
