# Generated by Django 5.1.3 on 2024-11-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_control_tipologia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='clasificacion',
        ),
        migrations.RemoveField(
            model_name='control',
            name='frecuencia',
        ),
        migrations.RemoveField(
            model_name='control',
            name='objetivo',
        ),
    ]
