# Generated by Django 5.1.3 on 2024-11-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_control_clasificacion_control_frecuencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encabezado',
            name='estado',
            field=models.CharField(choices=[('Sin iniciar', 'Sin iniciar'), ('En Proceso', 'En Proceso'), ('Terminado', 'Terminado'), ('No evaluado', 'No evaluado')], max_length=20),
        ),
    ]
