# Generated by Django 5.1.3 on 2024-11-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_alter_encabezado_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encabezado',
            name='fin',
        ),
        migrations.RemoveField(
            model_name='encabezado',
            name='inicio',
        ),
        migrations.AddField(
            model_name='encabezado',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
