# Generated by Django 5.1.3 on 2024-11-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_alter_validaciondiseño_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encabezado',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
