# Generated by Django 5.1.3 on 2024-11-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0016_alter_encabezado_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validaciondiseño',
            name='fecha_ejecucion',
            field=models.DateField(),
        ),
    ]
