# Generated by Django 5.1.3 on 2024-11-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0017_alter_validaciondiseño_fecha_ejecucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='prioridad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Baja', max_length=20),
            preserve_default=False,
        ),
    ]
